src/modules/seal/components/SealPositionOverview.tsx

Fetch SealPositionOverview data directly from the vault

---

src/modules/seal/components/SealRewardsOverview.tsx

Remove rate from Seal Rewards overview section

---

src/modules/app/components/WidgetPane.tsx

Adds hover link for seal supplied card

Add onClick for supplied seal card

---

src/modules/seal/components/SealWidgetPane.tsx

Add terms link to Seal widget

---

src/modules/seal/components/SealOverview.tsx
src/modules/ui/components/PopoverRateInfo.tsx

Add Seal borrow rate tooltip in details pane

---

package.json
pnpm-lock.yaml
src/locales/en.po
src/locales/es-AR.po
src/locales/es-ES.po
src/locales/es.po
src/locales/ko.po
src/modules/seal/components/SealHistory.tsx
src/modules/seal/components/SealPositionDetails.tsx

Add Seal history for each position

---

README.md
src/data/wagmi/config/config.default.ts
src/data/wagmi/config/testTenderlyChain.ts

Details here: https://app.shortcut.com/dux-makerdao/story/3238/add-base-network-config-and-dropdown
Note: PR is into new P1D feature branch

Add base mainnet and tenderly base networks to config

---

src/data/wagmi/config/config.default.ts
src/modules/app/components/WidgetNavigation.tsx
src/modules/app/components/WidgetPane.tsx

Context: https://app.shortcut.com/dux-makerdao/story/3239/update-widget-pane-component-to-show-relevant-widget-menu-based-on-network
Note: Still needs "coming soon" part, created a separate ticket for this to work on it once design is ready

Update widget menu based on chain

---

src/data/wagmi/config/config.default.ts
src/modules/layout/components/Header.tsx

Fixes https://app.shortcut.com/dux-makerdao/story/3259/seeing-horizontal-scroll

Fix container horizontal scroll on small screens

---

package.json
pnpm-lock.yaml

* Round up 1 wei the amount of USDS to approve when calling wipeAll
* Sort delegate list by total MKR delegated descending
* Fix error in the Seal borrow token input where the wrong max borrowable amount was display
* Resolves "insufficient collateral" issue when paying back debt

Misc seal fixes

---

package.json
pnpm-lock.yaml
src/modules/seal/components/SealWidgetPane.tsx

https://github.com/user-attachments/assets/d66b380d-19e7-4bf0-b439-1498bf303eb8

Select the right urn in the details pane when opening the seal widget

---

src/modules/seal/components/SealOverview.tsx

Reorder sections in Seal details pane

---

src/modules/app/components/WidgetNavigation.tsx

Fix widget content overflowing widget button on mobile

---

package.json
pnpm-lock.yaml
src/modules/config/context/ConfigContext.tsx
src/modules/config/types/user-config.ts
src/modules/seal/components/SealOverview.tsx
src/modules/seal/components/SealPositionDetails.tsx
src/modules/seal/components/SealPositionOverview.tsx
src/modules/seal/components/SealWidgetPane.tsx
src/modules/ui/components/BalanceCards.tsx

- get displayToken from widgetState callback & add to userConfig. Update TVL card when toggled.

hook into widget state

---

src/locales/en.po
src/locales/es-AR.po
src/locales/es-ES.po
src/locales/es.po
src/locales/ko.po
src/modules/seal/components/SealPositionOverview.tsx

show units in seal position overview

---

src/locales/en.po
src/locales/es-AR.po
src/locales/es-ES.po
src/locales/es.po
src/locales/ko.po
src/modules/auth/components/UnauthorizedPage.tsx
src/modules/layout/components/AuthWrapper.tsx
src/modules/layout/components/CustomConnectButton.tsx
src/modules/ui/context/ConnectedContext.tsx

- Update UnauthorizedPage component to handle optional authError and vpnError props
- Remove unused imports and variables in AuthWrapper component
- Update CustomConnectButton component to conditionally render UnauthorizedPage component when not authorized
- Add isAuthorized property to ConnectedContext to track user authorization status
- Update ConnectedProvider to include authData and vpnData in the context value
Before (see terms modal open behind VPN message):
After:

Refactor authentication and authorization logic

---

package.json
pnpm-lock.yaml
src/lib/constants.ts

seal region

---

src/modules/seal/components/SealRewardsOverview.tsx

show seal rewards TVL in dollars

---

src/components/ui/tabs.tsx
src/locales/en.po
src/locales/es-AR.po
src/locales/es-ES.po
src/locales/es.po
src/locales/ko.po
src/modules/app/components/WidgetNavigation.tsx
src/modules/app/components/WidgetPane.tsx
vite.config.ts

Based on the [latest design](https://www.figma.com/design/iYVZMpQHmx89If25IBplIc/sky.money-%E2%80%94-Final-Handoff?node-id=5465-18404&node-type=instance&m=dev)

Add coming soon icon to widget menu items

---

package.json
pnpm-lock.yaml
src/modules/ui/components/historyTable/HistoryRow.tsx

Get block explorer name dynamically

---

scripts/deleteVnet.ts
scripts/forkVnet.ts
src/components/NetworkSwitcher.tsx
src/data/wagmi/config/config.e2e.ts
src/data/wagmi/config/testTenderlyChain.ts
src/modules/app/components/WidgetNavigation.tsx
src/modules/layout/components/Header.tsx
src/modules/ui/components/ChainModal.tsx
src/test/e2e/tests/landing.spec.ts
src/test/e2e/utils/constants.ts
src/test/e2e/utils/distributeRewards.ts
src/test/e2e/utils/setBalance.ts
tenderlyTestnetData.json

- Add Tenderly base to e2e test suite
- Adapt network forking and deleting scripts to handle multiple network forks
- Add network switch tests

Add Tenderly base to e2e Wagmi config

---

src/modules/app/hooks/useSubgraphUrl.tsx
src/modules/rewards/components/RewardsSuppliersCard.tsx
src/modules/rewards/hooks/useRewardsSuppliersCount.tsx
src/modules/ui/components/TokenIcon.tsx
src/modules/ui/components/TokenIconWithBalance.tsx
src/modules/upgrade/components/UpgradedDaiToUsds.tsx
src/modules/upgrade/components/UpgradedMkrToSky.tsx

Update relevant hooks and components to take in a chainID and pass in mainnet on base

Show sky protocol stats on base balance detail pane

---

package.json
pnpm-lock.yaml

Attempt to resolve https://github.com/jetstreamgg/webapp/security/dependabot/16

Remove happy-dom v12

---

src/components/NetworkSwitcher.tsx
src/modules/layout/components/Header.tsx
src/modules/ui/components/ChainModal.tsx

Hide network label on mobile

---

src/locales/en.po
src/locales/es-AR.po
src/locales/es-ES.po
src/locales/es.po
src/locales/ko.po
src/modules/app/hooks/useActionForToken.tsx
src/modules/savings/components/SavingsWidgetPane.tsx
src/modules/ui/hooks/useRetainedQueryParams.tsx
src/modules/utils/validateSearchParams.ts

Handle balance cards actions on Base

---

src/modules/balances/components/BalancesModuleShowcase.tsx
src/modules/balances/components/ModuleCard.tsx

Hide Rewards and Upgrade cards from the balance detail pane on Base

---

src/modules/savings/components/SavingsBalanceDetails.tsx

Get sUsds balance using useTokenBalance instead.

remove use of useSsrAssetsToShares hook

---

package.json
pnpm-lock.yaml
src/modules/rewards/components/BoostedRewardsClaim.tsx
src/modules/savings/components/SavingsHistory.tsx
src/modules/savings/components/SavingsWidgetPane.tsx
src/modules/savings/components/SkySavingsRatePoolCard.tsx
src/modules/trade/components/TradeHistory.tsx
tailwind.config.ts

- Fix some build errors caused by recent changes in packages

Disable boosted rewards banner and claiming after Dec 31st

---

package.json
pnpm-lock.yaml

Approved in this PR: <https://github.com/jetstreamgg/webapp/pull/139>

bump widgets package

---

src/modules/balances/components/BalancesModuleShowcase.tsx
src/modules/balances/components/ModuleCard.tsx
src/modules/ui/components/ChainModal.tsx

https://github.com/user-attachments/assets/8c5b3903-7e27-41eb-b773-cd1583c35030

Ask user to switch to Ethereum if module card isn't available on base

---

src/modules/layout/components/UnsupportedNetworkPage.tsx

- switch network param
- remove autofocus on first button

fix unsupported network modal

---

src/components/NetworkSwitcher.tsx
src/modules/ui/components/ChainModal.tsx

Fix translations on network switcher

---

src/locales/en.po
src/locales/es-AR.po
src/locales/es-ES.po
src/locales/es.po
src/locales/ko.po
src/modules/balances/components/ModuleCard.tsx
src/modules/ui/components/ChainModal.tsx

https://github.com/user-attachments/assets/09b9171d-205e-4abf-99b8-7d4d35005460

Redirect module after network selection

---

README.md
package.json
pnpm-lock.yaml
src/locales/en.po
src/locales/es-AR.po
src/locales/es-ES.po
src/locales/es.po
src/locales/ko.po
src/modules/config/default-config.ts
src/modules/seal/components/SealOverview.tsx
src/modules/seal/getSealFaqItems.ts
src/modules/utils/validateSearchParams.ts
tenderlyTestnetData.json

Debt ceiling
